### PR TITLE
For simple list items, don't wrap in <p> tags

### LINKED ISSUE #57: Lists wrap items in <p> tags
Perhaps this observation isn't an 'issue' as the current behavior is accounted for in the tests, but the processing of lists is different in go-org than it is in an org export to HTML: it adds `<p>` tags around list items, where org export does not. Is it possible/does it make sense to catch the cases when the list item should be a paragraph within `WriteListItem` (I'm not sure what those cases are), and otherwise write the item as a string? Below is a simple example.

## Sample input
```
- this is a list
- another point
```

## org-mode export output
```html
<ul>
<li>this is a list</li>
<li>another point</li>
</ul>
```
(actually it adds a `org-ul` class by default)

## go-org output
```html
<ul>
<li>
<p>this is a list</p>
</li>
<li>
<p>another point</p>
</li>
</ul>
```

### PR DESCRIPTION
**Pull request by obar**
This also removes extra newlines for simple list items, see changes to tests for details.

Closes #57

### CODE REVIEW

**Comment by niklasfasching** [comment]
awesome, thx! I'll take a look on the weekend

**Comment by obar** [comment]
No rush whatsoever. I've been using this change with hugo and it's working as I expected, but that came as no surprise because you've put together quite a comprehensive test suite here. Thanks for that :)

**Comment by niklasfasching** [comment]
Thanks again for the pull request and patience :).

Would you be ok with me merging the following changes into your commit: [diff](https://github.com/niklasfasching/go-org/commit/693852290668e9b1781514a9bcc8756e2358d8f6)?

**Comment by obar** [comment]
Looks good to me, I don't think the slight changes in the behavior (as shown in the test diffs) matter In Real Life, and clearly your approach is more in line with the style of the rest of the code :grin:

Thanks for putting your time into this!

**Comment by niklasfasching** [comment]
closed with https://github.com/niklasfasching/go-org/commit/4d3a0999222efbfe37372f51b245951b85086a37

**Pull request closed without merging**
